service: serverless-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  # lambdaHashingVersion: '20201221'
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
          Resource:
            - arn:aws:dynamodb:us-east-1:907024394298:table/ItemTableNew


functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - http:
          path: /item
          method: post

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH